// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojhqbzggowzwowttvjnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qaHFiemdnb3d6d293dHR2am5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTgwMjUsImV4cCI6MjA2NTA3NDAyNX0.bpbhK-VWE_l6Fh2T83qitIMgDxJUBrOyVY7jqKmlmuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);